# Generated by Django 6.0 on 2025-12-07 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('charge', 'Списание'), ('refund', 'Возврат')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма операции', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Баланс до операции', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Баланс после операции', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Описание операции', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История баланса',
                'verbose_name_plural': 'История баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
