# Generated by Django 6.0 on 2025-12-07 20:15

import auth_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_balancehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Код страны (например: RU, US)', max_length=3, unique=True)),
                ('flag', models.CharField(default='🌍', help_text='Флаг эмодзи', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страна платежей',
                'verbose_name_plural': 'Страны платежей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=auth_app.models.generate_payment_id, help_text='4-значный ID', max_length=4, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], max_length=10)),
                ('method', models.CharField(choices=[('card', 'Карта (Card)'), ('sbp', 'СБП (SBP)')], max_length=10)),
                ('card_number', models.CharField(help_text='Номер карты', max_length=20)),
                ('card_holder', models.CharField(help_text='Имя владельца карты', max_length=255)),
                ('min_limit', models.DecimalField(decimal_places=2, default=10.0, help_text='Минимальный лимит', max_digits=10)),
                ('max_limit', models.DecimalField(decimal_places=2, default=1000.0, help_text='Максимальный лимит', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Страна платежа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.paymentcountry')),
                ('device', models.ForeignKey(blank=True, help_text='Привязанное устройство', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requisites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платежный реквизит',
                'verbose_name_plural': 'Платежные реквизиты',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'payment_id')},
            },
        ),
    ]
