# Generated by Django 6.0 on 2025-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_paymentcountry_paymentrequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequisite',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Активен ли реквизит (может быть изменено только администратором)'),
        ),
    ]
