# Generated by Django 5.2.4 on 2025-12-10 15:38

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_device_device_id_alter_balancehistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(default=auth_app.models.generate_user_id, editable=False, help_text='Уникальный публичный ID пользователя', max_length=8),
        ),
    ]
