# Generated by Django 5.2.4 on 2025-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_populate_payment_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequisite',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UAH', 'UAH')], max_length=10),
        ),
    ]
