# Generated by Django 5.2.4 on 2025-12-09 17:43

import crypto_payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True, verbose_name='TRC20 адрес')),
                ('private_key_encrypted', models.TextField(verbose_name='Зашифрованный приватный ключ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Крипто кошелёк',
                'verbose_name_plural': 'Крипто кошельки',
            },
        ),
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True, verbose_name='TRC20 адрес')),
                ('private_key_encrypted', models.TextField(verbose_name='Зашифрованный приватный ключ')),
                ('derivation_index', models.IntegerField(verbose_name='Индекс деривации')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платёжный адрес',
                'verbose_name_plural': 'Платёжные адреса',
            },
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=crypto_payments.models.generate_payment_id, max_length=8, unique=True, verbose_name='ID платежа')),
                ('currency', models.CharField(choices=[('USDT', 'USDT TRC20'), ('TRX', 'TRON')], default='USDT', max_length=10, verbose_name='Валюта')),
                ('amount_expected', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Ожидаемая сумма')),
                ('amount_received', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Полученная сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirming', 'Подтверждается'), ('completed', 'Завершён'), ('expired', 'Истёк'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Hash транзакции')),
                ('confirmations', models.IntegerField(default=0, verbose_name='Подтверждения')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='Callback URL')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('payment_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crypto_payments.paymentaddress', verbose_name='Адрес для оплаты')),
            ],
            options={
                'verbose_name': 'Крипто платёж',
                'verbose_name_plural': 'Крипто платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=128, unique=True, verbose_name='Hash транзакции')),
                ('from_address', models.CharField(max_length=64, verbose_name='От кого')),
                ('to_address', models.CharField(max_length=64, verbose_name='Кому')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('block_number', models.BigIntegerField(verbose_name='Номер блока')),
                ('confirmations', models.IntegerField(default=0, verbose_name='Подтверждения')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='crypto_payments.cryptopayment', verbose_name='Связанный платёж')),
            ],
            options={
                'verbose_name': 'Лог транзакции',
                'verbose_name_plural': 'Логи транзакций',
            },
        ),
    ]
