import { createContext, useContext, useEffect, useState } from "react";
import type { ReactNode } from "react";

type Language = "en" | "ru";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Dashboard
    "dashboard": "Dashboard",
    "verified": "Verified",
    "unverified": "Unverified",
    "pending": "Pending verification",
    "administrator": "Administrator",
    "user": "User",
    "available_balance": "Available Balance",
    "deposit_funds": "Deposit Funds",
    "frozen": "Frozen",
    "in_processing": "In processing",
    "net_pl": "Net P&L",
    "profit": "Profit",
    "loss": "Loss",
    "day": "DAY",
    "week": "WEEK",
    "month": "MONTH",
    "analytics": "Analytics",
    "income": "Income",
    "expenses": "Expenses",
    "recent_transactions": "Recent Transactions",
    "records": "records",
    "no_transactions": "No transactions yet",
    "start_depositing": "Start by depositing funds to your account",
    "type": "Type",
    "amount": "Amount",
    "before": "Before",
    "after": "After",
    "date": "Date",
    // Transaction types
    "deposit": "Deposit",
    "withdrawal": "Withdrawal",
    "refund": "Refund",
    "fee": "Fee",
    "adjustment": "Adjustment",
    "charge": "Charge",
    // Transactions page
    "transactions": "Transactions",
    "transaction_history": "Transaction History",
    "total_transactions": "Total Transactions",
    "total_income": "Total Income",
    "total_expense": "Total Expense",
    "all": "All",
    "all_time": "All Time",
    "today": "Today",
    // Payment
    "create_payment": "Create Payment",
    "payment_requisites": "Payment Requisites",
    // Common
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "cancel": "Cancel",
    "save": "Save",
    "delete": "Delete",
    "add": "Add",
    "edit": "Edit",
    "close": "Close",
    "status": "Status",
    "actions": "Actions",
    // Navigation
    "requisites": "Requisites",
    "deposits": "Deposits",
    "withdrawals": "Withdrawals",
    "devices": "Devices",
    "profile": "Profile",
    "logout": "Logout",
    "activity_history": "Activity History",
    "admin_panel": "Admin Panel",
    // Orders
    "orders": "Orders",
    "orders_in": "Incoming",
    "orders_out": "Outgoing",
    "no_orders": "No orders yet",
    "currency": "Currency",
    "requisite_id": "Requisite ID",
    "method": "Method",
    "completed_at": "Completed At",
    "completed": "Completed",
    "cancelled": "Cancelled",
    "wallet": "Wallet",
    // Admin
    "users": "Users",
    "merchants": "Merchants",
    "payments": "Payments",
    "verify": "Verify",
    "balance_management": "Balance Management",
    "user_management": "User Management",
    // Devices
    "my_devices": "My Devices",
    "add_device": "Add Device",
    "device_model": "Model",
    "device_name": "Name",
    "device_imei": "IMEI",
    "no_devices": "No devices added yet",
    // Deposit
    "deposit_crypto": "Deposit Crypto",
    "min_amount": "Minimum amount",
    "create_deposit": "Create Deposit",
    "payment_address": "Payment Address",
    "copy_address": "Copy Address",
    "address": "Address",
    "time_remaining": "Time Remaining",
    "awaiting_payment": "Awaiting Payment",
    "payment_completed": "Payment Completed",
    "payment_expired": "Payment Expired",
    "confirming": "Confirming",
    "deposit_history": "Deposit History",
    "no_deposits": "No deposits yet",
    "first_deposit_hint": "Create your first deposit to fund your account",
    "payment_details": "Payment Details",
    "quick_select": "Quick Select",
    "network": "Network",
    "confirmations": "Confirmations",
    "copy": "Copy",
    "copied": "Copied!",
    "check_status": "Check Status",
    "checking": "Checking...",
    "new_payment": "New",
    "creating": "Creating...",
    "deposits_processed": "Deposits are processed automatically after 19 network confirmations (~1 min)",
    // Auth
    "login": "Login",
    "register": "Register",
    "username": "Username",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "no_account": "Don't have an account?",
    "have_account": "Already have an account?",
    "auth.createAccount": "Create Account",
    "auth.registerSubtitle": "Use your Telegram username to register",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters",
    "auth.registerError": "Registration failed. Please try again.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.passwordHint": "At least 6 characters",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.or": "or",
    "auth.login": "Login",
    "auth.register": "Register",
    "common.loading": "Loading...",
    // Home
    "welcome": "Welcome to TrustX",
    "hero_subtitle": "Next-generation crypto payment processing platform",
    "get_started": "Get Started",
    "learn_more": "Learn More",
    // Arbitration
    "arbitration": "Arbitration",
    "dispute_resolution": "Dispute Resolution",
    "total_arbitrations": "Total Disputes",
    "arb_pending": "Pending",
    "arb_in_review": "In Review",
    "arb_resolved": "Resolved",
    "arb_rejected": "Rejected",
    "arb_status": "Arbitration Status",
    "resolution_status": "Resolution Status",
    "resolution_target": "Resolution Target",
    "res_none": "None",
    "res_refund": "Refund",
    "res_completed": "Completed",
    "res_partial": "Partial",
    "order_id": "Order ID",
    "order_status": "Order Status",
    "created_at": "Created At",
    "attachment": "Attachment",
    "comments": "Comments",
    "no_arbitrations": "No disputes yet",
    "no_arbitrations_hint": "All transactions are processed successfully",
    // Messages
    "messages": "Messages",
    "device_id": "Device ID",
    "received_by_device": "Received",
    "delivered_to_system": "Delivered",
    "notification_type": "Type",
    "message_from": "From",
    "order": "Order",
    "message": "Message",
    "no_messages": "No messages yet",
    "no_messages_hint": "Messages from devices will appear here",
    "created_before": "Created Before",
    "created_after": "Created After",
    "table_settings": "Table Settings",
    "payment": "Payment",
    "system": "System",
    "alert": "Alert",
    // Profile
    "your_profile": "Your Profile",
    "role": "Role",
    "user_login": "Login",
    "for_contact": "for contact",
    "change_password": "Change Password",
    "current_password": "Current Password",
    "new_password": "New Password",
    "save_password": "Save Password",
    "contacts": "Contacts",
    "new_login": "New Login",
    "new_telegram": "New Telegram",
    "save_info": "Save Information",
    "saving": "Saving...",
    "info_saved": "Information saved!",
    "password_changed": "Password changed!",
    "fill_all_fields": "Fill all fields",
    "fill_at_least_one": "Fill at least one field",
    "passwords_not_match": "Passwords do not match",
    "password_too_short": "Password must be at least 6 characters",
    // Withdrawals
    "withdraw_usdt_trc20": "Withdraw USDT TRC20",
    "create_withdrawal": "Create Withdrawal",
    "wallet_address": "Wallet Address",
    "create_withdrawal_request": "Create Withdrawal Request",
    "withdrawal_history": "Withdrawal History",
    "no_withdrawals": "No withdrawals yet",
    "withdrawal_request_created": "Withdrawal request created successfully",
    "withdrawal_failed": "Failed to create withdrawal",
    "min_withdrawal_amount": "Minimum withdrawal amount is 1 USDT",
    "insufficient_balance": "Insufficient balance",
    "invalid_trc20_address": "Invalid TRC20 wallet address",
    "confirm_cancel_withdrawal": "Are you sure you want to cancel this withdrawal?",
    "only_trc20_network": "Only TRC20 network is supported",
    "min_withdrawal": "Minimum withdrawal",
    "processing_time": "Processing time",
    "important": "Important",
    "processing": "Processing",
    "rejected": "Rejected",
    "network_error": "Network error",
    "deposit_explanation": "Enter the amount and select a merchant to create a deposit.",
    "send_deposit": "Send Deposit",
    "merchant_empty": "No merchants available",
    "amount_placeholder": "Enter amount",
  },
  ru: {
    // Dashboard
    "dashboard": "Панель управления",
    "verified": "Верифицирован",
    "unverified": "Не верифицирован",
    "pending": "Ожидание верификации",
    "administrator": "Администратор",
    "user": "Пользователь",
    "available_balance": "Доступный баланс",
    "deposit_funds": "Пополнить",
    "frozen": "Заморожено",
    "in_processing": "В обработке",
    "net_pl": "Чистая прибыль",
    "profit": "Прибыль",
    "loss": "Убыток",
    "day": "ДЕНЬ",
    "week": "НЕДЕЛЯ",
    "month": "МЕСЯЦ",
    "analytics": "Аналитика",
    "income": "Доход",
    "expenses": "Расход",
    "recent_transactions": "Последние транзакции",
    "records": "записей",
    "no_transactions": "Транзакций пока нет",
    "start_depositing": "Начните с пополнения счёта",
    "type": "Тип",
    "amount": "Сумма",
    "before": "До",
    "after": "После",
    "date": "Дата",
    // Transaction types
    "deposit": "Пополнение",
    "withdrawal": "Вывод",
    "refund": "Возврат",
    "fee": "Комиссия",
    "adjustment": "Корректировка",
    "charge": "Списание",
    // Transactions page
    "transactions": "Транзакции",
    "transaction_history": "История транзакций",
    "total_transactions": "Всего транзакций",
    "total_income": "Общий доход",
    "total_expense": "Общий расход",
    "all": "Все",
    "all_time": "За всё время",
    "today": "Сегодня",
    // Payment
    "create_payment": "Создать платёж",
    "payment_requisites": "Реквизиты",
    // Common
    "loading": "Загрузка...",
    "error": "Ошибка",
    "success": "Успешно",
    "cancel": "Отмена",
    "save": "Сохранить",
    "delete": "Удалить",
    "add": "Добавить",
    "edit": "Редактировать",
    "close": "Закрыть",
    "status": "Статус",
    "actions": "Действия",
    // Navigation
    "requisites": "Реквизиты",
    "deposits": "Депозиты",
    "withdrawals": "Вывод средств",
    "devices": "Устройства",
    "profile": "Профиль",
    "logout": "Выход",
    "activity_history": "История активности",
    "admin_panel": "Админ панель",
    // Orders
    "orders": "Заказы",
    "orders_in": "Входящие",
    "orders_out": "Исходящие",
    "no_orders": "Заказов пока нет",
    "currency": "Валюта",
    "requisite_id": "ID реквизита",
    "method": "Метод",
    "completed_at": "Дата завершения",
    "completed": "Завершён",
    "cancelled": "Отменён",
    "wallet": "Кошелек",
    // Admin
    "users": "Пользователи",
    "merchants": "Мерчанты",
    "payments": "Платежи",
    "verify": "Верифицировать",
    "balance_management": "Управление балансом",
    "user_management": "Управление пользователями",
    // Devices
    "my_devices": "Мои устройства",
    "add_device": "Добавить устройство",
    "device_model": "Модель",
    "device_name": "Название",
    "device_imei": "IMEI",
    "no_devices": "Устройства ещё не добавлены",
    // Deposit
    "deposit_crypto": "Пополнение криптовалютой",
    "min_amount": "Минимальная сумма",
    "create_deposit": "Создать депозит",
    "payment_address": "Адрес для оплаты",
    "copy_address": "Копировать адрес",
    "address": "Адрес",
    "time_remaining": "Осталось времени",
    "awaiting_payment": "Ожидание оплаты",
    "payment_completed": "Оплата завершена",
    "payment_expired": "Оплата истекла",
    "confirming": "Подтверждение",
    "deposit_history": "История депозитов",
    "no_deposits": "Депозитов пока нет",
    "first_deposit_hint": "Создайте первый депозит для пополнения счёта",
    "payment_details": "Детали платежа",
    "quick_select": "Быстрый выбор",
    "network": "Сеть",
    "confirmations": "Подтверждений",
    "copy": "Копировать",
    "copied": "Скопировано!",
    "check_status": "Проверить статус",
    "checking": "Проверка...",
    "new_payment": "Новый",
    "creating": "Создание...",
    "deposits_processed": "Депозиты обрабатываются автоматически после 19 подтверждений сети (~1 мин)",
    // Auth
    "login": "Войти",
    "register": "Регистрация",
    "username": "Имя пользователя",
    "password": "Пароль",
    "confirm_password": "Подтвердите пароль",
    "no_account": "Нет аккаунта?",
    "have_account": "Уже есть аккаунт?",
    "auth.createAccount": "Создать аккаунт",
    "auth.registerSubtitle": "Используйте ваш Telegram username для регистрации",
    "auth.passwordMismatch": "Пароли не совпадают",
    "auth.passwordTooShort": "Пароль должен быть не менее 6 символов",
    "auth.registerError": "Ошибка регистрации. Попробуйте ещё раз.",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.confirmPassword": "Подтвердите пароль",
    "auth.passwordHint": "Минимум 6 символов",
    "auth.alreadyHaveAccount": "Уже есть аккаунт?",
    "auth.or": "или",
    "auth.login": "Войти",
    "auth.register": "Регистрация",
    "common.loading": "Загрузка...",
    // Home
    "welcome": "Добро пожаловать в TrustX",
    "hero_subtitle": "Платформа криптовалютного процессинга нового поколения",
    "get_started": "Начать",
    "learn_more": "Узнать больше",
    // Arbitration
    "arbitration": "Арбитражи",
    "dispute_resolution": "Разрешение споров",
    "total_arbitrations": "Всего споров",
    "arb_pending": "Ожидают",
    "arb_in_review": "На рассмотрении",
    "arb_resolved": "Решены",
    "arb_rejected": "Отклонены",
    "arb_status": "Статус арбитража",
    "resolution_status": "Статус разрешения",
    "resolution_target": "Цель статуса разрешения",
    "res_none": "Нет",
    "res_refund": "Возврат",
    "res_completed": "Завершено",
    "res_partial": "Частично",
    "order_id": "ID заказа",
    "order_status": "Статус заказа",
    "created_at": "Дата создания",
    "attachment": "Вложение",
    "comments": "Комментарии",
    "no_arbitrations": "Споров пока нет",
    "no_arbitrations_hint": "Все транзакции обработаны успешно",
    // Messages
    "messages": "Сообщения",
    "device_id": "ID",
    "received_by_device": "Получено",
    "delivered_to_system": "Доставлено",
    "notification_type": "Тип",
    "message_from": "От кого",
    "order": "Заказ",
    "message": "Сообщение",
    "no_messages": "Сообщений пока нет",
    "no_messages_hint": "Сообщения от устройств появятся здесь",
    "created_before": "Создано до",
    "created_after": "Создано после",
    "table_settings": "Настройка таблицы",
    "payment": "Платёж",
    "system": "Системное",
    "alert": "Оповещение",
    // Profile
    "your_profile": "Ваш профиль",
    "role": "Роль",
    "user_login": "Логин",
    "for_contact": "для связи",
    "change_password": "Изменить пароль",
    "current_password": "Текущий пароль",
    "new_password": "Новый пароль",
    "save_password": "Сохранить пароль",
    "contacts": "Контакты",
    "new_login": "Новый логин",
    "new_telegram": "Новый Telegram",
    "save_info": "Сохранить информацию",
    "saving": "Сохранение...",
    "info_saved": "Информация сохранена!",
    "password_changed": "Пароль изменён!",
    "fill_all_fields": "Заполните все поля",
    "fill_at_least_one": "Заполните хотя бы одно поле",
    "passwords_not_match": "Пароли не совпадают",
    "password_too_short": "Пароль должен быть не менее 6 символов",
    // Withdrawals
    "withdraw_usdt_trc20": "Вывод USDT TRC20",
    "create_withdrawal": "Создать вывод",
    "wallet_address": "Адрес кошелька",
    "create_withdrawal_request": "Создать заявку на вывод",
    "withdrawal_history": "История выводов",
    "no_withdrawals": "Выводов пока нет",
    "withdrawal_request_created": "Заявка на вывод успешно создана",
    "withdrawal_failed": "Не удалось создать заявку",
    "min_withdrawal_amount": "Минимальная сумма вывода 1 USDT",
    "insufficient_balance": "Недостаточно средств",
    "invalid_trc20_address": "Неверный адрес TRC20 кошелька",
    "confirm_cancel_withdrawal": "Вы уверены, что хотите отменить этот вывод?",
    "only_trc20_network": "Поддерживается только сеть TRC20",
    "min_withdrawal": "Минимальный вывод",
    "processing_time": "Время обработки",
    "important": "Важно",
    "processing": "В обработке",
    "rejected": "Отклонён",
    "network_error": "Ошибка сети",
    "deposit_explanation": "Введите сумму и выберите мерчанта для депозита.",
    "send_deposit": "Отправить депозит",
    "merchant_empty": "Нет доступных мерчантов",
    "amount_placeholder": "Введите сумму",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "ru")) {
      setLangState(savedLang);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("language", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
